[package]
name = "limbo"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.30"
anyhow = "1.0.52"
byteorder = "1.4.3"
paste = "1.0.6"
serde_json = "1.0.73"
serde = "1.0.132"
serde_derive = "1.0.132"
tokio = { version = "1.15.0", features = ["full"] }
bytes = "1.1.0"
