[server]
host = "0.0.0.0"
port = 25565
# allow_bad_packets = false
log_level = "debug"

[info]
hidden = true
max_players = -1
hide_player_count = false
motd = "A Limbo Server"
# name = "Limbo"
# icon = "icon.png"
