[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.30"
byteorder = "1.4.3"
paste = "1.0.6"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
uuid = { version = "1.0.0-alpha.1", features = ["v4", "fast-rng"] }
