[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.40"
byteorder = "1.4.3"
paste = "1.0.12"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
uuid = { version = "1.3.2", features = ["v4", "fast-rng"] }
base64 = "0.21.0"
