[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
protocol = { path = "../protocol" }
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["full"] }
tracing = "0.1.37"
